#!/bin/sh

set -e

_CONTAINER_RUN="${LXC_ROOTFS_MOUNT}/run"
_CONTAINER_SHM="${LXC_ROOTFS_MOUNT}/dev/shm"
_CONTAINER_SYS="${LXC_ROOTFS_MOUNT}/sys"
_CONTAINER_CGROUP="${_CONTAINER_SYS}/fs/cgroup"
_CONTAINER_SYSTEMD="${_CONTAINER_CGROUP}/systemd"

# mount container /run
mount -t tmpfs tmpfs "${_CONTAINER_RUN}"

# mount /dev/shm
mkdir -p "${_CONTAINER_SHM}"
mount -t tmpfs tmpfs "${_CONTAINER_SHM}"

# mount container /sys
mount -t sysfs sysfs "${_CONTAINER_SYS}"

# let container /sys/fs/cgroup be a mount point
mount -t cgroup -o none,name=cbgroup.${LXC_NAME} cgroup "${_CONTAINER_CGROUP}"

# mount systemd cgroup in container
mkdir -p "${_CONTAINER_SYSTEMD}"
mount -t cgroup -o none,name=${LXC_NAME} cgroup "${_CONTAINER_SYSTEMD}"
